### ISSUE TITLE
Additional metadata

### ISSUE THREAD

**Issue by stephanbuettig** [citronalco/calibre-dnb#1]
Hi,

is it possible to read out the metadata "Edition (Ausgabe)" / "ISBN" and provide them together with the "IDN" for Calibre as parameters?

I would be very grateful!

**Comment by citronalco** [comment]
Can you give me an example?

**Comment by stephanbuettig** [comment]
At the moment the following metadata can be read with your plugin:
Comments (Kommentare) | Keywords (Schlagwörter) | Series (Serie) | Languages (Sprachen) | Publisher (Verlag) | Publication date (Veröffentlichungsdatum)

See e.g.: http://d-nb.info/999222430

In my opinion, the following entries are also significant:
1. Edition (Ausgabe): 6., neu bearb. und aktualisierte Aufl.
2. ISBN/EAN: 9783831719136
3. IDN: 999222430

Especially with the ISBN the book can be clearly assigned and a hyperlink to the entry in the DNB database can be generated with the IDN.

**Comment by citronalco** [comment]
The plugin already fetches ISBN and IDN (as "dnb-idn").
Both are "tags" in Calibre, and for an unknown reason Calibre doesn't allow to enable or disable fetching tags in the plugin configuration, so fetching those tags is always enabled.

I can add the edition, but I'm not quite sure where to put it. Calibre has no dedicated field for that, so if you don't have a better idea I'll put it in the title (e.g. "Mord am Tegernsee : Ein Bayern-Krimi :  3. Aufl.")

**Comment by stephanbuettig** [comment]
Thanks for these informations. I didn't know about the tricky fetching.

 I think your solution is the most practicable one. Is there a workaround to display the ISBN, IDN and the edition in a separate column? For the ISBN this works at least with the plugin "Extract ISBN".

**Comment by citronalco** [comment]
I've added an option to the plugin's "settings" widget where you can enable appending the edition to the title.

Which columns are shown has basically nothing to do with any plugin. Most likely you want to add user defined columns: This has nothing to do with the plugin, it's a  you can do on your own, as described i.e. here: http://blog.calibre-ebook.com/2011/11/calibre-custom-columns.html
For a column named "IDN" showing the dnb-idn tag you'd set:

- lookup name: idn
- column heading: IDN
- template: {identifiers:select(dnb-idn)}
