### ISSUE TITLE
Plugin fails to install

### ISSUE THREAD

**Issue by workflowsguy** [citronalco/calibre-dnb#2]
Hi,
I tried to install the plugin into Calibre. However, when opening the zip file in the "Erweiterung aus Datei laden" dialog, the following error message is displayed:

calibre, version 3.27.1
FEHLER: Nicht abgefangener Fehler: <b>InvalidPlugin</b>:The plugin in u'/Users/guy/Download/calibre-dnb-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.27.1  embedded-python: True is64bit: True
Darwin-15.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.6.0', 'Darwin Kernel Version 15.6.0: Wed May  2 21:04:22 PDT 2018; root:xnu-3248.73.10~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.11.6', ('', '', ''), 'x86_64')
Interface language: de
Successfully initialized third party plugins: Library Codes (1, 0, 34) && English Noun Frequency (1, 0, 8) && Clean Metadata (0, 0, 6) && X-Ray Creator (3, 1, 2) && NormComment (0, 0, 2) && Save Composite Custom Columns (1, 1, 0) && Find Duplicates (1, 6, 3) && Manage Series (1, 2, 8) && Consolidate All Library Metadata (2, 0, 32) && Job Spy (1, 0, 129) && Extract ISBN (1, 4, 4) && Overdrive Link (2, 28, 1) && Goodreads (1, 1, 14) && MultiColumnSearch (1, 0, 74) && Quality Check (1, 9, 11) && Barnes & Noble (1, 2, 15) && QuarantineAndScrub (3, 6, 103) && Overdrive Link* (2, 28, 1)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 471, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 60, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 192, in load
  File "site-packages/calibre/customize/zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'/Users/guy/Download/calibre-dnb-master.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by citronalco** [comment]
Please use the file from "release" (direct link: https://github.com/citronalco/calibre-dnb/releases/download/v2.0.5/dnb-metadata-plugin-2.0.5.zip)

**Comment by workflowsguy** [comment]
Thank you, it works!

**Comment by citronalco** [comment]
I'm glad to hear that.
DNB changed its website a few days ago.  This led to an extreme slowdown when fetching metadata without SRU token. I've just published a new release which fixes that: https://github.com/citronalco/calibre-dnb/releases/download/v2.0.6/dnb-metadata-plugin-2.0.6.zip
You have to install it manually, as the plugin has no updater yet.
