### ISSUE TITLE
Sru aces token doesn´t work

### ISSUE THREAD

**Issue by Lawer1** [citronalco/calibre-dnb#3]
I generate the sru access token. The sru access token has many numers and letters.

I write/copy the sru acces code in the plugin.

It doesn´t work. I got no metadatas. Without the access token code i got the metadatas.

What´s wrong??

**Comment by citronalco** [comment]
Most likely either the service was temporarily down or the token is wrong.
Currently the plugin has no detailed error reporting...yet.

Can you check the log (open calibre's "Jobs", then double click on the failed job's line)?
There should be some long lines starting with "Query URL:". Please open the URL in your preferred web browser. If you see something like "Authentication errorNo Account for AccessToken" your token is wrong.

**Comment by Lawer1** [comment]
I try it again. 

You need to type the token in the field of the plugin. To use the copy function doesnt´work.

After I type the same token code - it works.

Thanks a lot.

**Comment by citronalco** [comment]
Glad to hear that!
Let me know in case you find any other issues.
